version: '3.8'

services:
  app:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - ".:/myapp"
    ports:
      - "4500:4500"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://spritle:12345@db/sample_todo_development
      REDIS_URL: redis://localhost:6379/1
      RAILS_ENV: development

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - ".:/myapp"
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://spritle:12345@db/sample_todo_development
      REDIS_URL: redis://localhost:6379/1
      RAILS_ENV: development

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: spritle
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sample_todo_development
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
